### ISSUE TITLE
No way to specify root, assumed root is sometimes incorrect

### ISSUE THREAD

**Issue by sean-esper** [Spoutnik97/danger-plugin-code-coverage#1]
All of my test coverage was returning zero even though the coverage report had values.

Poking around a bit it looks like in `getCoverageForFile` we assemble the file path of each changed/added file to pull from the constructed coverage map.

In my case I ended up with
filePath: frontend/src/app/... 
rootDir: .../frontend
combined .../frontend/frontend/src/app...
but the true file path in the map is .../frontend/src/app...

I changed getCoverageForFile:16 to be     
`return coverageByPath[getFileAbsolutePath(filePath.split('/').slice(1).join('/'))];` and now the results are coming back as expected.

I can open a PR, but I know very little about how you use this so I wasnt sure if it was something differing between our setups.

**Comment by sean-esper** [comment]
Thinking about it, I think this is because my frontend repository is not in the root of my project. In that case it seems like we might need to expose an option for the root? Not really sure how thats generally handled

**Comment by Spoutnik97** [comment]
@sean-esper thanks for your feedbacks. Please feel free to open a PR. 
I will work on the root directory soon. 
Could you rename your issue title for the next users looking for a no-root directory issue please ?

**Comment by slantzjr** [comment]
PR created: #2

**Comment by Spoutnik97** [comment]
Will be available in v1.2.0
