### ISSUE TITLE
Broken link to display color

### ISSUE THREAD

**Issue by christophemenager** [Spoutnik97/danger-plugin-code-coverage#10]
Hi @Spoutnik97 ;)

It looks like the website placehold.it you use to display colors is replaced by place-hold.it
I tried to create a PR with this fix but write permissions on your repo are restricted 🥺 

![image](https://user-images.githubusercontent.com/17217868/114207902-2a8faf80-995d-11eb-88f7-b1f9f918e2ac.png)

**Comment by gairal** [comment]
Hi,

placehold.it redirects to placeholder.com now.
They may have taken the domain but don't have a proper TLS certificate yet

Seems to work as well
https://via.placeholder.com/15/red/000000/?text=+

**Comment by Spoutnik97** [comment]
Thanks a lot for the info @christophemenager !
I deploy a fix now 😉

P.S: Have you tried to fork the project and create a PR on the repo? Or did you push a new branch directly on the repo ?

**Comment by Spoutnik97** [comment]
Fixed in the version 1.1.7
