### ISSUE TITLE
Ignore patterns does not work

### ISSUE THREAD

**Issue by eranrodrig** [Spoutnik97/danger-plugin-code-coverage#14]
```
pluginOptions.forEach(options => {
    const filterFiles = (file: string) => {
      let isFileDisplayed = true
      options.ignoreCoveragePattern.forEach(pattern => {
        if (file.includes(pattern)) {
          isFileDisplayed = false
        }
      })
      return isFileDisplayed
    }
```
This code has a bug since 'includes' does not match patterns. a.includes(b) checks if b is a substring of a.
Correct me if I'm wrong, but I'm guessing you are trying to match regex patterns.
To do that you can use the **match** method, which accepts a regex as an argument.

**Comment by Spoutnik97** [comment]
@eranrodrig yes I could do this, but the string patterns won't be considered...
I try to modify according to your comment

**Comment by eranrodrig** [comment]
@Spoutnik97 Maybe you could consider adding this as another option that is called ignoreRegexPatterns?

**Comment by Spoutnik97** [comment]
@eranrodrig  from the version 1.1.9, ignoreCoveragePattern includes regex patterns
