### ISSUE TITLE
Danger local doesnt work.

### ISSUE THREAD

**Issue by probosckie** [Spoutnik97/danger-plugin-code-coverage#15]
I have a setup like this:
https://github.com/probosckie/jest-danger-threshold-check/tree/feat/danger-integrate

when I'm trying to run this with

```
yarn danger local
```

But it's giving an error like this:

```
Danger: ⅹ Failing the build, there is 1 fail.
## Failures
An error occurred when getting the code coverage: /Users/prabhas.joshi/code/jest-danger-threshold-check/coverage/coverage-final.json: Unexpected end of JSON input. Danger exits with code: undefined
```

When I run it on CI also - it gives this error:
https://github.com/probosckie/jest-danger-threshold-check/pull/1

**Comment by Spoutnik97** [comment]
You need to check the output of your coverage file. It seems to be an
incorrect JSON file

Le lun. 27 déc. 2021 à 17:36, Prabhas Joshi ***@***.***> a
écrit :

**Comment by probosckie** [comment]
yes it works now.
can the readme - mention that we should be generating the coverage in the expected file before we run the danger file.


I was able to create a very simple example repo and pr which works - which i think would be useful for new users
Pr -  https://github.com/probosckie/jest-danger-threshold-check/pull/2
repo: branch: https://github.com/probosckie/jest-danger-threshold-check/tree/feat/danger-integrate
