### ISSUE TITLE
Allow include patterns as well as ignore

### ISSUE THREAD

**Issue by wilhen01** [Spoutnik97/danger-plugin-code-coverage#16]
I've been playing with the plugin this afternoon and it's generally pretty good, but my `ignoreCoveragePattern` array has been growing steadily while playing. It would be much easier to be able to specifically include things (e.g. everything under a `src/` directory rather than having to individually ignore things. 

I realise it would be a breaking change to remove the `ignoreCoveragePattern` option but could we have an `includeCoveragePattern` option as well?

**Comment by Spoutnik97** [comment]
@wilhen01 from the version 1.1.9, ignoreCoveragePattern includes regex patterns
