### ISSUE TITLE
yarn.lock and .gitignore get into coverage

### ISSUE THREAD

**Issue by beshur** [Spoutnik97/danger-plugin-code-coverage#19]
Hi.

I have Jest coverage configured only for js/ts files. 
There is no yarn.lock and .gitignore in coverage_final.json

However this plugin gets all the changes files in the commit and compares it against coverage, resulting in 0% for yarn.lock etc.

I don't want to see anything `src/` in this message.
What should I do?

**Comment by Spoutnik97** [comment]
Hey,
you can ignore the files you don't want to see in the coverage thanks to this property in the config file 
` ignoreCoveragePattern: [".test.", ".snap"],` 

So for instance you can add : 
` ignoreCoveragePattern: [".lock", ".gitignore"],` in your config

**Comment by beshur** [comment]
Thank you.

I have quite a number of files in the root. Okay, I'll try.
